#!/bin/bash
# Islamic AI Agent - Complete Training & Deployment Guide

echo "╔════════════════════════════════════════════════════════════════════════╗"
echo "║                   ISLAMIC AI AGENT - TRAINING COMPLETE                 ║"
echo "║              With Authentic Knowledge from 35,796 Documents            ║"
echo "╚════════════════════════════════════════════════════════════════════════╝"
echo ""

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}📊 TRAINING STATISTICS${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}✓ Total Documents Indexed${NC}:        35,796"
echo -e "${GREEN}✓ Knowledge Base Size${NC}:           59 MB"
echo -e "${GREEN}✓ Compressed Index Size${NC}:        48.4 MB"
echo -e "${GREEN}✓ Average Document Size${NC}:        605 characters"
echo ""

echo -e "${BLUE}📚 CONTENT DISTRIBUTION${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "  📖 Quranic Verses          20,925 documents (58.5%) - 4 translations"
echo -e "  📚 Hadith Collections      14,462 documents (40.4%) - 8 major collections"
echo -e "  📖 Tafsir/Commentary           31 documents (0.1%)  - Authentic interpretations"
echo -e "  🔍 Scholarly Sources          378 documents (1.1%)  - Islamic jurisprudence"
echo ""

echo -e "${BLUE}🌍 LANGUAGE SUPPORT${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "  🇬🇧 English          35,778 documents (99.9%)"
echo -e "  🇸🇦 Arabic              11 documents (0.0%)"
echo -e "  🇵🇰 Urdu                 7 documents (0.0%)"
echo ""

echo -e "${BLUE}✨ FEATURES ENABLED${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "  ${GREEN}✓${NC} Authentic Response Optimizer     - Best quality responses"
echo -e "  ${GREEN}✓${NC} Advanced Response Builder         - Quran prioritization"
echo -e "  ${GREEN}✓${NC} Multi-Source Integration         - Quran + Hadith + Tafsir + Scholarly"
echo -e "  ${GREEN}✓${NC} Quality Scoring System           - Shows confidence (59-90%)"
echo -e "  ${GREEN}✓${NC} Source Attribution               - With specific references"
echo -e "  ${GREEN}✓${NC} Fast Response Generation         - < 1 second response time"
echo ""

echo -e "${BLUE}🚀 QUICK START${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "  ${YELLOW}1. Start Backend${NC}"
echo "     $ cd /Users/fahadiqbal/Downloads/Latest\\ Projects/Islamic-AIAgent"
echo "     $ source .venv/bin/activate"
echo "     $ python backend/api/web_api.py"
echo ""
echo -e "  ${YELLOW}2. Query the API${NC}"
echo "     $ curl -X POST http://localhost:5010/api/chat \\"
echo "       -H 'Content-Type: application/json' \\"
echo "       -d '{\"message\": \"What are the Five Pillars of Islam?\"}'"
echo ""
echo -e "  ${YELLOW}3. Check Health${NC}"
echo "     $ curl http://localhost:5010/api/health | jq"
echo ""

echo -e "${BLUE}📝 EXAMPLE QUERIES${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Query 1: What is the significance of the Five Pillars in Islam?"
echo "           Response: Quran + Hadith + Scholarly Analysis"
echo "           Quality: 59-66% (Multiple sources balanced)"
echo ""
echo "  Query 2: What does the Quran say about charity and helping the poor?"
echo "           Response: 3 Hadiths from Sahih al-Bukhari with verse numbers"
echo "           Quality: 74-90% (High - Sahih collections)"
echo ""
echo "  Query 3: Explain Islamic jurisprudence and sources of Sharia law"
echo "           Response: Fiqh fundamentals + Hadith examples"
echo "           Quality: 63-72% (Scholarly + Hadith)"
echo ""

echo -e "${BLUE}🔧 MAINTENANCE COMMANDS${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "  ${YELLOW}Retrain Model${NC} (after adding new data)"
echo "  $ python scripts/comprehensive_training.py"
echo ""
echo -e "  ${YELLOW}Restart Backend${NC}"
echo "  $ pkill -f web_api.py"
echo "  $ python backend/api/web_api.py"
echo ""
echo -e "  ${YELLOW}View Backend Logs${NC}"
echo "  $ tail -f /tmp/backend.log"
echo ""
echo -e "  ${YELLOW}Add New Islamic Knowledge${NC}"
echo "  $ cp your_file.txt backend/knowledge/data/"
echo "  $ python scripts/comprehensive_training.py"
echo ""

echo -e "${BLUE}📂 KEY FILES${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Training:"
echo "    • scripts/comprehensive_training.py       - Full training pipeline"
echo ""
echo "  Optimization:"
echo "    • backend/utils/authentic_response_optimizer.py  - Quality responses"
echo "    • backend/utils/advanced_response_builder.py     - Formatting"
echo ""
echo "  API:"
echo "    • backend/api/web_api.py                  - REST API server"
echo ""
echo "  Knowledge Base:"
echo "    • backend/knowledge/data/                 - 38 files, 59 MB"
echo "    • backend/knowledge/bm25_index.pkl        - Trained index (48.4 MB)"
echo ""
echo "  Documentation:"
echo "    • TRAINING_COMPLETE.md                    - Full training documentation"
echo ""

echo -e "${BLUE}🎯 RESPONSE QUALITY LEVELS${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  90%+ : Sahih Hadith (highly authenticated)"
echo "  74%+ : Well-sourced multiple perspectives"
echo "  59%+ : Good coverage with proper attribution"
echo "  <59% : Basic but accurate responses"
echo ""

echo -e "${BLUE}💡 TIPS FOR BEST RESULTS${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1. Be Specific: 'What are Islamic rules for prayer?' vs 'Prayer'"
echo "  2. Use Islamic Terms: 'What is Zakat?' gets better results"
echo "  3. Check Quality Scores: Higher % = More authenticated sources"
echo "  4. Look at Sources: See which collection each piece comes from"
echo "  5. Consult Scholars: For specific Fiqh rulings, consult qualified scholars"
echo ""

echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✨ YOUR ISLAMIC AI AGENT IS FULLY TRAINED & READY!${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Backend URL:  http://localhost:5010"
echo "API Endpoint: POST /api/chat"
echo "Health Check: GET /api/health"
echo ""
echo "May Allah accept our efforts and guide us to the truth! 🤲"
echo ""
